### PR TITLE
Removing marker::NoCopy and adding feature raw

### PR DESCRIPTION
**Pull request by aleyan**

### CODE REVIEW

**Comment by bfops** [comment]
Hi Alex. At first glance, I don't get what's going on. I should probably add comments to this effect: the reason that GLContext is `NoCopy` is so that it won't accidentally outlive the OpenGL context (e.g. by being copied to a long-running function or long-living data structure). Did `NoCopy` get removed or something?

Thanks!

**Comment by aleyan** [comment]
I don't know when, but it was marked deprecated on yesterday's and today's nightly. Looks like structs are not copyable by default unless they implement the Copy trait.

> src/gl_context.rs:28:11: 28:25 error: use of deprecated item: structs are by default not copyable, #> [deny(deprecated)] on by default
src/gl_context.rs:28   nocopy: marker::NoCopy,

Mind you, I am pretty new to rust (less than 24 hours) and just trying to get playform to compile on the latest nightly. What I did may be not the right thing.

**Comment by bfops** [comment]
> Looks like structs are not copyable by default unless they implement the Copy trait.

This is definitely true. The docs for `NoCopy` made it sound like there could be "accidental" `Copy` implementations if `GLContext` were to be included in another struct, but I can't really think of how that would happen. I think this change make sense.

**Comment by bfops** [comment]
Also welcome to Rust! I think the IRC's pretty helpful for general Rust things, but definitely feel free to ping me with questions or thoughts or whatever on my Rust stuff. I love talking about Playform =P.

**Comment by aleyan** [comment]
Thanks! I will be submitting a Playform PR to bring it up to date with the nightlies once I figure out how to work around the thread::scoped deprecation.

**Comment by bfops** [comment]
Awesome, thanks! I guess I should `rustup` every now and again..

The deprecation makes me sad. IIRC, using `scoped` and careful lifetiming meant that we could put things on the stack, and maybe some other niceties. @cgaebel pointed out that we could basically just rewrite our own version of `scoped` that keeps the same lifetime enforcements (and maybe with some extra `unsafe` qualifiers). I don't feel particularly strong either way though; if it's easier to just replace it with `spawn` and a few heap allocations, that's probably fine too.

**Pull request merged**
